version: "3.8"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=p_management