spring:
  application:
    name: gerenciamento_pessoas
  datasource:
    url: jdbc:postgresql://dpg-cor5tf7sc6pc73djrltg-a.virginia-postgres.render.com:5432/p_management_mzxz
    username: admin
    password: 7U4Tfb0OWfOBuhYLe73xHzrpAlV9bio0
  jpa:
    properties:
      hibernate:
        dialect:
          org:
            hibernate:
              dialect:
                PostgreSQLDialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true