spring:
  application:
    name: gerenciamento_pessoas
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${DATABASE}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect:
          org:
            hibernate:
              dialect:
                PostgreSQLDialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true